# SOURCE: https://github.com/actions/starter-workflows/blob/main/ci/maven.yml
# This workflow will build a Java project with Maven
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    ## https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/
    ## Branches used macro '$default-branch' pointing to 'main', only feasable in workflow-templates!
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  slim-linter:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    # We want the slim-linter to run first! always()
    if: always()
    needs: slim-linter

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 9
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Show java version
      run: java -version
    - name: Build with Maven
      run: mvn -B package --file pom.xml
