# SOURCE: https://github.com/actions/starter-workflows/blob/main/ci/maven.yml
# This workflow will build a Java project with Maven
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    ## https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/
    ## Branches used macro '$default-branch' pointing to 'main', only feasable in workflow-templates!
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 9
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Show java version
      run: java -version
    - name: Build with Maven
      run: mvn -B package --file pom.xml
